version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
      - db
    ports:
      - 3330:3330
    volumes:
      - ./frontend:/app
    environment:
      - VITE_BASE_URL_PORT=3331
      - VITE_SERVER_PORT=3330
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 3331:3331
    volumes:
      - ./backend:/app
    environment:
      - PORT=3331
      - JWT_SECRET=12345678aA
      - DATABASE_URL=mysql://root:1234@db:3306/TaskManagerDev
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3336:3306
    volumes:
      - ebytrMySQL:/var/lib/mysql

volumes:
  ebytrMySQL:
