version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: "ebytr_database_container"
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
